# This rule is not used by the project image-policy-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over security.shieldx-bot.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterimagepolicy-admin-role
rules:
- apiGroups:
  - security.shieldx-bot.io
  resources:
  - clusterimagepolicies
  verbs:
  - '*'
- apiGroups:
  - security.shieldx-bot.io
  resources:
  - clusterimagepolicies/status
  verbs:
  - get
