# This rule is not used by the project image-policy-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the security.shieldx-bot.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterimagepolicy-editor-role
rules:
- apiGroups:
  - security.shieldx-bot.io
  resources:
  - clusterimagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.shieldx-bot.io
  resources:
  - clusterimagepolicies/status
  verbs:
  - get
