apiVersion: security.shieldx-bot.io/v1
kind: ClusterImagePolicy
metadata:
  name: prod-strict-policy-security
spec:
  action: Enforce
  images:
    - glob: "docker.io/library/nginx:*"
  publicKeys:
    - secretRef: cosign-pub-key
  namespaces:
    - security
